--Query 1: Total revenue and total orders

SELECT
count (*) AS total_orders,
sum (net_revenue_aed) AS total_revenue
FROM ecommerce_sales_uae

--Query 2: Revenue by Category, Highest to lowest

SELECT
category,
sum(net_revenue_aed) AS total_revenue
FROM
ecommerce_sales_uae
GROUP BY category
ORDER BY total_revenue DESC

--Query 3: Revenue by City, Highest to lowest

SELECT
city,
sum(net_revenue_aed) AS total_revenue
FROM
ecommerce_sales_uae
GROUP BY city
ORDER BY total_revenue DESC

--Query 4: Monthly revenue trend

SELECT
strftime('%Y-%m', order_date) AS order_month,
sum(net_revenue_aed) AS total_revenue
FROM
ecommerce_sales_uae
GROUP BY order_month
ORDER BY order_month;

--Query 5: Average order Value

SELECT
customer_segment,
avg(net_revenue_aed) AS avg_order_value,
count(*) AS num_orders
FROM
ecommerce_sales_uae
GROUP BY customer_segment
Order by avg_order_value DESC

--Query 6: Average rating and number of orders by delivery days..

SELECT
case
WHEN delivery_days <= 2 THEN '1-2 days'
WHEN delivery_days <= 4 THEN '3-4 days'
WHEN delivery_days <= 6 THEN '5-6 days'
ELSE '7+ days'
END AS delivery_band,
avg(rating) AS avg_rating,
count(*) AS num_orders
FROM
ecommerce_sales_uae
GROUP BY delivery_band
ORDER BY delivery_band;

--Query 7: Average order value by discount percentage

SELECT
CASE
WHEN discount_pct = 0 THEN '0%'
WHEN discount_pct <= 10 THEN'1-10%'
WHEN discount_pct <= 20 THEN'11- 20%'
ELSE '21%+'
END AS discount_band,
AVG(net_revenue_aed) AS avg_order_value,
count(*) AS num_orders
FROM
ecommerce_sales_uae
GROUP BY discount_band
ORDER BY discount_band;


--Query 8: Top 5 categories by average rating.

SELECT
category,
avg(rating) AS avg_rating,
count(*) AS num_orders
FROM
ecommerce_sales_uae
GROUP BY category
ORDER BY avg_rating DESC
LIMIT 5


--Query 9: Revenue generated by payment method

SELECT
payment_method,
sum(net_revenue_aed) AS total_revenue,
count(*) AS num_orders
FROM
ecommerce_sales_uae
GROUP BY payment_method
ORDER BY total_revenue DESC

--Query 10:

SELECT
city,
avg(discount_pct) AS avg_discount
FROM
ecommerce_sales_uae
GROUP BY city
ORDER BY avg_discount DESC




